openapi: 3.0.3
info:
  title: Hub API
  description: APIs for dashboard and transmission
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

tags:
  - name: Dashboard
  - name: Transmission
  - name: Configuration

paths:
  /system-configuration:
    get:
      tags:
        - Configuration
      summary: Get system configuration
      operationId: getSystemConfiguration
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemConfiguration"
  /containers/{containerId}/clusters/{clusterId}/pack-metrics/{packId}:
    get:
      tags:
        - Dashboard
      summary: Get the metrics of a pack
      operationId: getPackMetrics
      parameters:
        - $ref: "#/components/parameters/containerId"
        - $ref: "#/components/parameters/clusterId"
        - $ref: "#/components/parameters/packId"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackMetricsResponse"
  /containers/{containerId}/clusters/{clusterId}/pack-overviews:
    get:
      tags:
        - Dashboard
      summary: Get the metrics of all packs in a cluster
      operationId: listPackOverviews
      parameters:
        - $ref: "#/components/parameters/containerId"
        - $ref: "#/components/parameters/clusterId"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListPackOverviewsResponse"
  /overview:
    get:
      tags:
        - Dashboard
      summary: Get dashboard overview
      operationId: getDashboardOverview
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Overview"
  /transmit-data:
    post:
      tags:
        - Transmission
      summary: transmit data to the server
      operationId: transmitData
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransmitDataRequest"
      responses:
        "201":
          description: Successful response
components:
  schemas:
    TransmitDataRequest:
      type: object
      properties:
        eisMeasurements:
          type: array
          items:
            $ref: "#/components/schemas/EisMeasurement"
        generatedRecords:
          type: array
          items:
            $ref: "#/components/schemas/GeneratedRecord"
        packMetricsRecords:
          type: array
          items:
            $ref: "#/components/schemas/PackMetricsRecord"
    PackMetricsResponse:
      type: object
      properties:
        metrics:
          $ref: "#/components/schemas/PackMetrics"
        measurements:
          type: array
          items:
            $ref: "#/components/schemas/EisMeasurement"
    EisMeasurement:
      type: object
      properties:
        containerId:
          type: string
        clusterId:
          type: string
        packId:
          type: string
        cellId:
          type: string
        realImpedance:
          type: number
          format: double
        frequency:
          type: number
          format: double
        imaginaryImpedance:
          type: number
          format: double
        voltage:
          type: number
          format: double
        creationTime:
          type: string
          format: date-time
        temperature:
          type: number
          format: double
    Diagnostic:
      type: object
      properties:
        seiParameter:
          type: integer
        temperature:
          type: number
          format: double
        dendritesParameter:
          type: integer
        electrolyteParameter:
          type: integer
        polarizationPotential:
          type: number
          format: double
        conductivity:
          type: number
          format: double
    Cluster:
      type: object
      properties:
        id:
          type: string
        packs:
          type: array
          items:
            type: string
    Container:
      type: object
      properties:
        id:
          type: string
        clusters:
          type: array
          items:
            $ref: "#/components/schemas/Cluster"
    SystemConfiguration:
      type: object
      properties:
        containers:
          type: array
          items:
            $ref: "#/components/schemas/Container"
    Overview:
      type: object
      properties:
        monthlyInspections:
          type: integer
        totalInspections:
          type: integer
          format: int64
        totalMeasurements:
          type: integer
          format: int64
        totalRiskySamples:
          type: integer
        cumulativeRiskIdentifications:
          type: integer
    PackOverview:
      type: object
      properties:
        packId:
          type: string
        dispersionCoefficient:
          type: number
          format: double
        averageImpedanceRecords:
          type: array
          items:
            $ref: "#/components/schemas/AverageImpedanceRecord"
    ListPackOverviewsResponse:
      type: object
      properties:
        records:
          type: array
          items:
            $ref: "#/components/schemas/PackOverview"
    AverageImpedanceRecord:
      type: object
      properties:
        frequency:
          type: number
          format: double
        averageImpedance:
          type: number
          format: double
    PackMetrics:
      type: object
      properties:
        packId:
          type: string
        dispersionCoefficient:
          type: number
          format: double
        safetyRate:
          type: number
          format: double
        diagnostics:
          type: object
          properties:
            max:
              $ref: "#/components/schemas/Diagnostic"
            min:
              $ref: "#/components/schemas/Diagnostic"
        packHealthHistory:
          type: array
          items:
            $ref: "#/components/schemas/PackHealth"
    PackHealth:
      type: object
      properties:
        safetyRate:
          type: number
          format: double
        creationTime:
          type: string
          format: date
    GeneratedRecord:
      type: object
      properties:
        containerId:
          type: string
        clusterId:
          type: string
        packId:
          type: string
        cellId:
          type: string
        creationTime:
          type: string
          format: date-time
        dispersionCoefficient:
          type: number
          format: double
        temperature:
          type: number
          format: double
        seiParameter:
          type: integer
        dendritesParameter:
          type: integer
        electrolyteParameter:
          type: integer
        polarizationPotential:
          type: number
          format: double
        conductivity:
          type: number
          format: double
    PackMetricsRecord:
      type: object
      properties:
        containerId:
          type: string
        clusterId:
          type: string
        packId:
          type: string
        creationTime:
          type: string
          format: date-time
        dispersionCoefficient:
          type: number
          format: double
        safetyRate:
          type: number
          format: double

  parameters:
    containerId:
      in: path
      required: true
      name: containerId
      schema:
        type: string
    packId:
      in: path
      required: true
      name: packId
      schema:
        type: string
    clusterId:
      in: path
      schema:
        type: string
      required: true
      name: clusterId
    dateFrom:
      in: query
      schema:
        type: string
        format: date-time
      required: false
      name: dateFrom
    dateTo:
      in: query
      schema:
        type: string
        format: date-time
      required: false
      name: dateTo
