server:
  port: 8080
  tomcat:
    max-http-post-size: 10MB
config:
  cors:
    allowed-origins: ${FRONTEND_ORIGIN:http://localhost:3000}
spring:
  application:
    name: hub
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432}/xdra?reWriteBatchedInserts=true
    username: xdra
    password: Test!123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 10000
      pool-name: HikariCP
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 200
        show_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
